server {
    listen 80;
    absolute_redirect off;

    location /aitube/ {
        alias /usr/share/nginx/html/;
        index index.html;
        try_files $uri $uri/ /aitube/index.html;
    }

    location = /aitube {
        return 301 /aitube/;
    }
}
